stages:
  - deploy-staging

deploy:
  stage: deploy-staging
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - ssh-keyscan 192.168.1.246 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
     # Connect to the server and deploy
    - ssh user@192.168.1.246 "cd /var/www/html/timeteccrm/timetec-crm && git pull"
  only:
    - master